spring:
    datasource:
        hikari:
            minimum-idle: 5
            maximum-pool-size: 20
            jdbc-url: jdbc:mysql://118.195.179.140/appz9001
            driver-class-name: com.mysql.cj.jdbc.Driver
            username: root
            password: root
mybatis:
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    configuration:
        map-underscore-to-camel-case: true
pagehelper:
    helperDialect: mysql
    reasonable: true
server:
    port: 8090
        