spring:
    datasource:
        hikari:
            minimum-idle: 2
            maximum-pool-size: 5
            jdbc-url: jdbc:mysql://110.42.233.64/appz9001
            driver-class-name: com.mysql.cj.jdbc.Driver
            username: root
            password: mysql.xyz
    security:
        oauth2:
            client:
                client-id: client
                client-secret: secret
                access-token-uri: http://localhost:8090/oauth/token
                check-token-access: http://localhost:8090/oauth/check_token
    redis:
        database: 0
        host: 118.195.179.140
        port: 6379
        password: appz9001.abc
mybatis:
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    configuration:
        map-underscore-to-camel-case: true
pagehelper:
    helperDialect: mysql
    reasonable: true
server:
    port: 8090