spring:
    datasource:
        hikari:
            minimum-idle: 5
            maximum-pool-size: 20
            jdbc-url: jdbc:mysql://118.195.179.140/appz9001
            driver-class-name: com.mysql.cj.jdbc.Driver
            username: root
            password: root
    security:
        oauth2:
            client:
                client-id: client
                client-secret: secret
                access-token-uri: http://localhost:8090/oauth/token
                check-token-access: http://localhost:8090/oauth/check_token
    redis:
        database: 0
        host: 118.195.179.140
        port: 6379
        jedis:
            pool:
                max-active: 8
                max-idle: 8
                min-idle: 0
        timeout: 10000

mybatis:
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    configuration:
        map-underscore-to-camel-case: true
pagehelper:
    helperDialect: mysql
    reasonable: true
server:
    port: 8090